name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@ptrumpis'

      - name: Temporarily update package name with scope
        run: |
          sed -i 's/"name": "wayback.js"/"name": "@ptrumpis\/wayback.js"/' package.json

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/ --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
